#!/bin/bash
set -e

# - Permissions
chmod 755 /etc/gnimble/wifi/*.sh
chmod uog+rw /etc/gnimble/stories/*

# - Handle dependencies
python3 -m pip install weasyprint flask pillow gunicorn htmldocx html2text psutil --break-system-packages

# - Manage wifi selection settings
SUDOERS_FILE="/etc/sudoers.d/connect_sh"
cat << EOF > "$SUDOERS_FILE"
ALL ALL=(root) NOPASSWD: /etc/gnimble/wifi/connect.sh
ALL ALL=(root) NOPASSWD: /etc/gnimble/wifi/mount.sh
ALL ALL=(root) NOPASSWD: /etc/gnimble/wifi/umount.sh
EOF
chmod 440 "$SUDOERS_FILE"

# - Handle server script
systemctl daemon-reload
systemctl enable --now gnimble-server.service
systemctl enable --now gnimble-update.service